# Generated by Django 3.1.14 on 2023-05-25 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DCAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(blank=True, max_length=64, null=True)),
                ('start_measure', models.IntegerField(blank=True, null=True)),
                ('stop_measure', models.IntegerField(blank=True, null=True)),
                ('is_cadence', models.BooleanField()),
                ('cadence_kind', models.CharField(blank=True, max_length=64, null=True)),
                ('cadence_alter', models.CharField(blank=True, max_length=64, null=True)),
                ('cadence_role_cantz', models.CharField(blank=True, max_length=16, null=True)),
                ('cadence_role_tenz', models.CharField(blank=True, max_length=16, null=True)),
                ('cadence_final_tone', models.CharField(blank=True, max_length=16, null=True)),
                ('voices_p6_up', models.CharField(blank=True, max_length=16, null=True)),
                ('voices_p6_lo', models.CharField(blank=True, max_length=16, null=True)),
                ('voices_p3_up', models.CharField(blank=True, max_length=16, null=True)),
                ('voices_p3_lo', models.CharField(blank=True, max_length=16, null=True)),
                ('voices_53_up', models.CharField(blank=True, max_length=16, null=True)),
                ('voices_53_lo', models.CharField(blank=True, max_length=16, null=True)),
                ('other_formulas', models.CharField(blank=True, max_length=64, null=True)),
                ('other_pres_type', models.CharField(blank=True, max_length=64, null=True)),
                ('voice_role_up1_nim', models.CharField(blank=True, max_length=16, null=True)),
                ('voice_role_lo1_nim', models.CharField(blank=True, max_length=16, null=True)),
                ('voice_role_up2_nim', models.CharField(blank=True, max_length=16, null=True)),
                ('voice_role_lo2_nim', models.CharField(blank=True, max_length=16, null=True)),
                ('voice_role_dux1', models.CharField(blank=True, max_length=16, null=True)),
                ('voice_role_com1', models.CharField(blank=True, max_length=16, null=True)),
                ('voice_role_dux2', models.CharField(blank=True, max_length=16, null=True)),
                ('voice_role_com2', models.CharField(blank=True, max_length=16, null=True)),
                ('voice_role_un_oct', models.CharField(blank=True, max_length=16, null=True)),
                ('voice_role_fifth', models.CharField(blank=True, max_length=16, null=True)),
                ('voice_role_fourth', models.CharField(blank=True, max_length=16, null=True)),
                ('voice_role_above', models.CharField(blank=True, max_length=16, null=True)),
                ('voice_role_below', models.CharField(blank=True, max_length=16, null=True)),
                ('other_contrapuntal', models.CharField(blank=True, max_length=128, null=True)),
                ('text_treatment', models.CharField(blank=True, max_length=128, null=True)),
                ('repeat_kind', models.CharField(blank=True, max_length=64, null=True)),
                ('earlier_phrase', models.CharField(blank=True, max_length=16, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('repeat_exact_varied', models.CharField(blank=True, max_length=16, null=True)),
                ('needs_review', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Observation',
                'verbose_name_plural': 'Observations',
            },
        ),
        migrations.CreateModel(
            name='DCBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(db_index=True, unique=True)),
                ('title', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('complete_title', models.CharField(blank=True, max_length=128, null=True)),
                ('publisher', models.CharField(blank=True, max_length=64, null=True)),
                ('place_publication', models.CharField(blank=True, max_length=64, null=True)),
                ('date', models.CharField(blank=True, max_length=64, null=True)),
                ('volumes', models.CharField(blank=True, max_length=64, null=True)),
                ('part_st_id', models.CharField(blank=True, max_length=16, null=True)),
                ('part_cb_id', models.CharField(blank=True, max_length=16, null=True)),
                ('num_compositions', models.CharField(blank=True, max_length=16, null=True)),
                ('num_pages', models.CharField(blank=True, max_length=16, null=True)),
                ('location', models.CharField(blank=True, max_length=16, null=True)),
                ('rism', models.CharField(blank=True, max_length=16, null=True)),
                ('cesr', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='DCContentBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('published', models.BooleanField()),
                ('content_type', models.CharField(choices=[('news', 'News'), ('featured', 'Featured Reconstruction'), ('block', 'Front Page Block')], default='block', max_length=32)),
                ('position', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
            ],
            options={
                'verbose_name': 'Content Block',
                'verbose_name_plural': 'Content Blocks',
            },
        ),
        migrations.CreateModel(
            name='DCFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('attachment', models.FileField(upload_to='%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='DCPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(db_index=True, max_length=16, null=True, unique=True)),
                ('surname', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('given_name', models.CharField(blank=True, max_length=64, null=True)),
                ('birth_date', models.CharField(blank=True, max_length=16, null=True)),
                ('death_date', models.CharField(blank=True, max_length=16, null=True)),
                ('active_date', models.CharField(blank=True, max_length=16, null=True)),
                ('alt_spelling', models.CharField(blank=True, max_length=64, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='DCPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_id', models.CharField(db_index=True, max_length=16, unique=True)),
                ('book_position', models.IntegerField(blank=True, max_length=16, null=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('composer_src', models.CharField(blank=True, max_length=64, null=True)),
                ('forces', models.CharField(blank=True, max_length=16, null=True)),
                ('print_concordances', models.CharField(blank=True, max_length=128, null=True)),
                ('ms_concordances', models.CharField(blank=True, max_length=128, null=True)),
                ('pdf_link', models.CharField(blank=True, max_length=255, null=True)),
                ('mei_link', models.CharField(blank=True, max_length=255, null=True)),
                ('audio_link', models.CharField(blank=True, max_length=255, null=True)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duchemin.dcbook', to_field='book_id')),
                ('composer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duchemin.dcperson', to_field='person_id')),
            ],
            options={
                'verbose_name': 'Piece',
                'verbose_name_plural': 'Pieces',
            },
        ),
        migrations.CreateModel(
            name='DCReconstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachments', models.ManyToManyField(to='duchemin.DCFile')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duchemin.dcpiece', to_field='piece_id')),
                ('reconstructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duchemin.dcperson', to_field='person_id')),
            ],
            options={
                'verbose_name': 'Reconstruction',
                'verbose_name_plural': 'Reconstructions',
            },
        ),
        migrations.CreateModel(
            name='DCUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=64, null=True)),
                ('favourited_analysis', models.ManyToManyField(blank=True, db_index=True, to='duchemin.DCAnalysis')),
                ('favourited_piece', models.ManyToManyField(blank=True, db_index=True, to='duchemin.DCPiece')),
                ('favourited_reconstruction', models.ManyToManyField(blank=True, db_index=True, to='duchemin.DCReconstruction')),
                ('person', models.ForeignKey(blank=True, help_text='Link this account with a DuChemin User', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='duchemin.dcperson')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DCPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_id', models.IntegerField(db_index=True, unique=True)),
                ('phrase_num', models.IntegerField(blank=True, null=True)),
                ('phrase_start', models.CharField(blank=True, max_length=4, null=True)),
                ('phrase_stop', models.CharField(blank=True, max_length=4, null=True)),
                ('phrase_text', models.CharField(blank=True, max_length=255, null=True)),
                ('rhyme', models.CharField(blank=True, max_length=64, null=True)),
                ('piece_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duchemin.dcpiece', to_field='piece_id')),
            ],
            options={
                'verbose_name': 'Phrase',
                'verbose_name_plural': 'Phrases',
                'ordering': ['piece_id', 'phrase_num'],
            },
        ),
        migrations.CreateModel(
            name='DCNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='duchemin.dcpiece')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='DCComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='duchemin.dcpiece')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.AddField(
            model_name='dcanalysis',
            name='analyst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='duchemin.dcperson', to_field='person_id'),
        ),
        migrations.AddField(
            model_name='dcanalysis',
            name='composition_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='duchemin.dcpiece', to_field='piece_id'),
        ),
        migrations.AddField(
            model_name='dcanalysis',
            name='phrase_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='duchemin.dcphrase', to_field='phrase_id'),
        ),
    ]
